Repository Cockple/Cockple_BE, pull requests merged in 2025-08, with the labels that each got.

#223 [fix/#208] 모임 요청 파라미터 Enum 변환 및 검증 로직 수정
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateDTO.java
  src/main/java/umc/cockple/demo/domain/party/enums/ActiveDay.java
  src/main/java/umc/cockple/demo/domain/party/enums/ActivityTime.java
  src/main/java/umc/cockple/demo/domain/party/enums/ParticipationType.java
  src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
  src/main/java/umc/cockple/demo/domain/party/repository/PartyRepositoryCustomImpl.java
  src/main/java/umc/cockple/demo/global/enums/Keyword.java
Labels: 🔧 FIX

#225 [debug#224] 나이 검증 출생년도 비교로 변경 및 관련 필드명 변경
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
  src/main/java/umc/cockple/demo/domain/member/domain/Member.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
Labels: 🕷️ BUG

#228 [feat/#227] 모임 탈퇴 시, 자동으로 채팅방 퇴장 코드 구현
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessage.java
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatRoomMember.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🛠️ FEAT

#237 [fix/#236] 대회 이미지 저장 방식 변경
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/domain/ContestImg.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordCreateDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordUpdateDTO.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java
Labels: 🔧 FIX

#229 [feat/#192] 새로운 운동 추천 캘린더 조회 API 구현
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseRecommendationCalendarDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepositoryCustom.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepositoryCustomImpl.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
Labels: 🛠️ FEAT

#246 [feat/#232] 신규 멤버 추천 API 구현
  src/main/java/umc/cockple/demo/domain/member/repository/MemberRepository.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyMemberSuggestionDTO.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
Labels: 🛠️ FEAT

#249 [feat/#248] 웹소켓 기본 설정 및 연결 관리 구현
  build.gradle
  src/main/java/umc/cockple/demo/domain/chat/dto/WebSocketMessageDTO.java
  src/main/java/umc/cockple/demo/domain/chat/enums/WebSocketMessageType.java
  src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/umc/cockple/demo/global/config/WebSocketConfig.java
Labels: 🛠️ FEAT

#253 [feat/#162] 알림 추가 로직 구현
  src/main/java/umc/cockple/demo/domain/notification/converter/NotificationConverter.java
  src/main/java/umc/cockple/demo/domain/notification/domain/Notification.java
  src/main/java/umc/cockple/demo/domain/notification/dto/CreateNotificationRequestDTO.java
  src/main/java/umc/cockple/demo/domain/notification/enums/NotificationTarget.java
  src/main/java/umc/cockple/demo/domain/notification/exception/NotificationErrorCode.java
  src/main/java/umc/cockple/demo/domain/notification/repository/NotificationRepository.java
  src/main/java/umc/cockple/demo/domain/notification/service/NotificationCommandService.java
  src/main/java/umc/cockple/demo/domain/notification/service/NotificationMessageGenerator.java
Labels: 🛠️ FEAT

#270 [feat/#262] 모임 초대 처리 API 구현
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/domain/PartyInvitation.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyInviteActionDTO.java
  src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🛠️ FEAT

#281 [feat/#279] 초기 채팅방 조회 API 구현
  src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatRoomMember.java
  src/main/java/umc/cockple/demo/domain/chat/dto/ChatRoomDetailDTO.java
  src/main/java/umc/cockple/demo/domain/chat/enums/MessageType.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatMessageRepository.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomRepository.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryService.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
Labels: 🛠️ FEAT

#293 [debug/#289] 전송 이미지 크기 설정
  src/main/resources/application.yml
Labels: 🕷️ BUG

#282 [feat/#280] 과거 메시지 조회 API 구현
  src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/dto/ChatMessageDTO.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatMessageRepository.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryService.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
Labels: 🛠️ FEAT

#259 [feat/#250] 메시지 전송 기능 구현
  build.gradle
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessage.java
  src/main/java/umc/cockple/demo/domain/chat/dto/WebSocketMessageDTO.java
  src/main/java/umc/cockple/demo/domain/chat/exception/ChatErrorCode.java
  src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomRepository.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatWebSocketService.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberRepository.java
  src/test/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandlerTest.java
Labels: 🛠️ FEAT

#304 [fix/#286] 모임 채팅방 저장 방식 변경
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatRoom.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🔧 FIX

#303 [fix/#302] 하드코딩->로그인 아이디로 변경
  src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
Labels: 🔧 FIX

#309 [feat/#284] 개인 채팅 slice기반 목록 조회 구현
  src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/dto/DirectChatRoomDTO.java
  src/main/java/umc/cockple/demo/domain/chat/enums/Direction.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomRepository.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryService.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
Labels: 🛠️ FEAT

#313 [feat/#305] redis 기본 설정 추가 및 도입
  build.gradle
  src/main/java/umc/cockple/demo/global/config/RedisConfig.java
  src/main/java/umc/cockple/demo/global/config/redisTest/RedisTest.java
  src/main/resources/application.yml
Labels: 🛠️ FEAT

#316 [debug#315] 임시로 웹소켓 경로 허용
  src/main/java/umc/cockple/demo/global/config/SecurityConfig.java
Labels: 🕷️ BUG

#314 [feat/#265] 채팅방 구독 로직 구현
  src/main/java/umc/cockple/demo/domain/chat/dto/MemberConnectionInfo.java
  src/main/java/umc/cockple/demo/domain/chat/dto/WebSocketMessageDTO.java
  src/main/java/umc/cockple/demo/domain/chat/events/ChatEventListener.java
  src/main/java/umc/cockple/demo/domain/chat/events/ChatMessageSendEvent.java
  src/main/java/umc/cockple/demo/domain/chat/events/ChatRoomSubscriptionEvent.java
  src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatWebSocketService.java
  src/main/java/umc/cockple/demo/domain/chat/service/SubscriptionService.java
  src/main/java/umc/cockple/demo/domain/chat/service/WebSocketBroadcastService.java
Labels: 🛠️ FEAT

#310 [feat/#287] 다운로드 토큰 발급 구현
  src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessage.java
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessageFile.java
  src/main/java/umc/cockple/demo/domain/chat/domain/DownloadToken.java
  src/main/java/umc/cockple/demo/domain/chat/dto/ChatDownloadTokenDTO.java
  src/main/java/umc/cockple/demo/domain/chat/exception/ChatErrorCode.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatFileRepository.java
  src/main/java/umc/cockple/demo/domain/chat/repository/DownloadTokenRepository.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatFileService.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatFileServiceImpl.java
Labels: 🛠️ FEAT

#318 [feat/#288] 파일 다운로드 구현
  src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
  src/main/java/umc/cockple/demo/domain/chat/exception/ChatErrorCode.java
  src/main/java/umc/cockple/demo/domain/chat/repository/DownloadTokenRepository.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatFileService.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatFileServiceImpl.java
  src/main/java/umc/cockple/demo/domain/image/service/ImageService.java
Labels: 🛠️ FEAT

#321 [feat/#300] 채팅방 구독 해제 로직
  src/main/java/umc/cockple/demo/domain/chat/events/ChatEventListener.java
  src/main/java/umc/cockple/demo/domain/chat/events/ChatRoomSubscriptionEvent.java
  src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/umc/cockple/demo/domain/chat/service/SubscriptionService.java
Labels: 🛠️ FEAT

#323 [feat/#311] 파일 다운로드 리팩토링 / 파일 업로드 API 구현
  src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatFileServiceImpl.java
  src/main/java/umc/cockple/demo/domain/image/controller/ImgController.java
  src/main/java/umc/cockple/demo/domain/image/dto/FileUploadDTO.java
  src/main/java/umc/cockple/demo/domain/image/dto/ImageUploadDTO.java
  src/main/java/umc/cockple/demo/domain/image/dto/ImageUploadResponseDTO.java
  src/main/java/umc/cockple/demo/domain/image/exception/S3ErrorCode.java
  src/main/java/umc/cockple/demo/domain/image/service/ImageService.java
  src/main/java/umc/cockple/demo/global/enums/DomainType.java
  src/main/java/umc/cockple/demo/global/enums/ImgType.java
Labels: 🛠️ FEAT, 🔧 FIX

#327 [feat/#322] 탈퇴 회원 시큐리티 필터에서 검증
  src/main/java/umc/cockple/demo/domain/member/domain/Member.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
  src/main/java/umc/cockple/demo/global/config/SecurityConfig.java
  src/main/java/umc/cockple/demo/global/exception/RestAuthenticationEntryPoint.java
  src/main/java/umc/cockple/demo/global/oauth2/service/KakaoOauthService.java
  src/main/java/umc/cockple/demo/global/security/filter/JwtAuthenticationFilter.java
Labels: 🛠️ FEAT

#329 [feat/#328] JWT null인 경우 예외 처리
  src/main/java/umc/cockple/demo/domain/member/exception/MemberErrorCode.java
  src/main/java/umc/cockple/demo/global/jwt/domain/JwtTokenProvider.java
Labels: 🛠️ FEAT

#330 [feat/#296] 키워드 추가 API 구현
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyKeywordDTO.java
  src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
  src/main/java/umc/cockple/demo/domain/party/repository/PartyKeywordRepository.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🛠️ FEAT

#331 [feat/#301] 채팅방 자동 읽음 로직 구현
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/dto/WebSocketMessageDTO.java
  src/main/java/umc/cockple/demo/domain/chat/events/ChatEventListener.java
  src/main/java/umc/cockple/demo/domain/chat/events/ChatMessageReadEvent.java
  src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatReadService.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatWebSocketService.java
  src/main/java/umc/cockple/demo/domain/chat/service/SubscriptionService.java
Labels: 🛠️ FEAT

#341 [fix/#326] 특정 지역으로 조회 시, addr2가 전체인 모임도 조회되도록 수정
  src/main/java/umc/cockple/demo/domain/party/repository/PartyRepositoryCustomImpl.java
Labels: 🔧 FIX

#349 [fix#348] 운동 신청 시 급수 조건이 맞지 않더라도 신청할 수 있도록 변경
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseValidator.java
Labels: 🔧 FIX

#356 [feat/#355] 운동 수정을 위한 조회 API 구현
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseEditDetailDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
Labels: 🛠️ FEAT

#363 [fix/#361] 모임 관련 검증 수정사항 반영
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🔧 FIX

#364 [fix/#362] 현재 (목록/개인) 채팅방 목록 조회 및 검색 API에서 채팅방이 없을 때 에러 던지는 걸 빈 배열 던지는 걸로 반환
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
Labels: 🔧 FIX

#360 [debug#359] 웹소켓 설정에서 프론트 배포 주소 CORS 허용
  src/main/java/umc/cockple/demo/global/config/WebSocketConfig.java
Labels: 🕷️ BUG

#373 [feat/#367] 채팅 보낼 때 이미지와 파일도 같이 보낼 수 있도록 로직 추가
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessage.java
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessageImg.java
  src/main/java/umc/cockple/demo/domain/chat/dto/WebSocketMessageDTO.java
  src/main/java/umc/cockple/demo/domain/chat/events/ChatEventListener.java
  src/main/java/umc/cockple/demo/domain/chat/events/ChatMessageSendEvent.java
  src/main/java/umc/cockple/demo/domain/chat/exception/ChatErrorCode.java
  src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatWebSocketService.java
Labels: 🛠️ FEAT

#374 [fix/#339] 급수 검색에서 포함된 글자만으로도 조회되도록 수정
  src/main/java/umc/cockple/demo/domain/member/repository/MemberRepositoryCustomImpl.java
Labels: 🔧 FIX

#377 [fix/#375] 모임 상세 조회 응답 필드 추가
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyDetailDTO.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
Labels: 🔧 FIX

#395 [feat/#372] WebSocket 요청마다 에러를 반환하도록 개선
  src/main/java/umc/cockple/demo/domain/chat/dto/WebSocketMessageDTO.java
  src/main/java/umc/cockple/demo/domain/chat/events/ChatEventListener.java
  src/main/java/umc/cockple/demo/domain/chat/exception/ChatErrorCode.java
  src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatFileServiceImpl.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatImageServiceImpl.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatValidator.java
  src/main/java/umc/cockple/demo/domain/chat/service/websocket/ChatReadService.java
  src/main/java/umc/cockple/demo/domain/chat/service/websocket/ChatSendService.java
  src/main/java/umc/cockple/demo/domain/chat/service/websocket/MessageReadCreationService.java
  src/main/java/umc/cockple/demo/domain/chat/service/websocket/SubscriptionReadProcessingService.java
  src/main/java/umc/cockple/demo/domain/chat/service/websocket/SubscriptionService.java
  src/main/java/umc/cockple/demo/domain/chat/service/websocket/WebSocketMessageService.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberQueryService.java
Labels: 🛠️ FEAT

#396 [fix/#379] 프로필 사진 수정 오류
  src/main/java/umc/cockple/demo/domain/member/domain/Member.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
Labels: 🔧 FIX

#406 [chore/#405] 리프레시 토큰 재발급 텀 줄이기
  src/main/java/umc/cockple/demo/global/oauth2/service/KakaoOauthService.java
Labels: 🎵 CHORE

#408 [fix/#407] 내 운동 리스트 조회 API에 급수 필드 추가
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/MyExerciseListDTO.java
Labels: 🔧 FIX

#409 [feat/#343] Redis 기반 채팅방 구독 관리 시스템 구축
  build.gradle
  src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
  src/main/java/umc/cockple/demo/domain/chat/service/websocket/RedisSubscriptionService.java
  src/main/java/umc/cockple/demo/domain/chat/service/websocket/SubscriptionService.java
  src/main/resources/application.yml
Labels: 🛠️ FEAT

#414 [debug/#413] Redis에서 Jackson 직렬화 문제 해결
  src/main/java/umc/cockple/demo/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 🕷️ BUG

#416 [debug/#415] Redis에서 객체 조회해올 때 역직렬화 문제 해결
  src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
  src/main/java/umc/cockple/demo/domain/chat/dto/ChatRoomListCacheDTO.java
  src/main/java/umc/cockple/demo/domain/chat/dto/LastMessageCacheDTO.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
  src/main/java/umc/cockple/demo/domain/chat/service/websocket/ChatRoomListCacheService.java
  src/main/java/umc/cockple/demo/global/admin/controller/AdminController.java
  src/main/java/umc/cockple/demo/global/config/RedisConfig.java
Labels: 🕷️ BUG

#422 [fix/#421] profile imgKey null, 비어있는 값 모두 체크
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
Labels: 🔧 FIX
