Repository Cockple/Cockple_BE, pull requests merged in 2025-07, with the labels that each got.

#4 [feat/#3] 글로벌 예외 처리 로직 구현
  build.gradle
  src/main/java/umc/cockple/demo/global/exception/GeneralException.java
  src/main/java/umc/cockple/demo/global/exception/GlobalExceptionHandler.java
  src/main/java/umc/cockple/demo/global/response/BaseResponse.java
  src/main/java/umc/cockple/demo/global/response/code/BaseErrorCode.java
  src/main/java/umc/cockple/demo/global/response/code/status/CommonErrorCode.java
  src/main/java/umc/cockple/demo/global/response/dto/ErrorReasonDTO.java
Labels: 🛠️ FEAT

#7 [fix#6] GlobalExceptionHandler에서 @ExceptionHandler 충돌 문제 해결
  src/main/java/umc/cockple/demo/global/exception/GlobalExceptionHandler.java
Labels: 🕷️ BUG

#27 [feat/#20] 모임 만들기 API 구현
  src/main/java/umc/cockple/demo/domain/member/domain/MemberParty.java
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
  src/main/java/umc/cockple/demo/domain/party/domain/PartyAddr.java
  src/main/java/umc/cockple/demo/domain/party/domain/PartyImg.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyAddrCreateCommand.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateCommand.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateRequestDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateResponseDTO.java
  src/main/java/umc/cockple/demo/domain/party/exception/MemberErrorCode.java
  src/main/java/umc/cockple/demo/domain/party/exception/MemberException.java
  src/main/java/umc/cockple/demo/domain/party/repository/PartyAddrRepository.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
  src/main/java/umc/cockple/demo/global/s3/ImageService.java
Labels: 🛠️ FEAT

#45 [Feat/#44] 대회 기록 삭제 API 구현
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/domain/Contest.java
  src/main/java/umc/cockple/demo/domain/contest/domain/ContestVideo.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDeleteCommand.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDeleteResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDetailResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/repository/ContestRepository.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
Labels: 🛠️ FEAT

#52 [feat/#51] 특정 회원 운동 취소 API 구현
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/domain/Exercise.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseManagerCancelRequestDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/exception/ExerciseErrorCode.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
Labels: 🛠️ FEAT

#54 [feat/#46] 내 대회 기록 상세조회 API 구현
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDetailResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
Labels: 🛠️ FEAT

#58 [feat/#55] 내 대회 기록 리스트 조회 (전체, 미입상) API 구현
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/domain/Contest.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordSimpleResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/repository/ContestRepository.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java
  src/main/java/umc/cockple/demo/global/enums/MedalType.java
Labels: 🛠️ FEAT

#60 [feat/#57] 운동 삭제 API 구현
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseDeleteResponseDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
Labels: 🛠️ FEAT

#65 [refactor/#61] 운동 참여자 수 계산 로직 수동 증가에서 사이즈 계산으로 변경
  src/main/java/umc/cockple/demo/domain/exercise/domain/Exercise.java
Labels: 🌟 REFACT

#71 [feat/#70] 다른 회원의 대회 기록 상세조회 API 구현
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDetailResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java
Labels: 🛠️ FEAT

#74 [feat/#73] 다른 회원의 대회 기록 리스트 (전체, 미입상) API 구현
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java
Labels: 🛠️ FEAT

#69 [feat/#66] 운동 수정 API 구현
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/domain/Exercise.java
  src/main/java/umc/cockple/demo/domain/exercise/domain/ExerciseAddr.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseAddrUpdateCommand.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseUpdateCommand.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseUpdateRequestDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseUpdateResponseDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/exception/ExerciseErrorCode.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
Labels: 🛠️ FEAT

#83 [feat/#80] 회원주소 추가 API 구현
  src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
  src/main/java/umc/cockple/demo/domain/member/converter/MemberConverter.java
  src/main/java/umc/cockple/demo/domain/member/domain/Member.java
  src/main/java/umc/cockple/demo/domain/member/domain/MemberAddr.java
  src/main/java/umc/cockple/demo/domain/member/domain/ProfileImg.java
  src/main/java/umc/cockple/demo/domain/member/dto/CreateMemberAddrDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/UpdateProfileRequestDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/request/CreateMemberAddRequestDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/request/UpdateProfileRequestDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/response/CreateMemberAddrResponseDTO.java
  src/main/java/umc/cockple/demo/domain/member/exception/MemberErrorCode.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
Labels: 🛠️ FEAT

#90 [refactor/#88] 메달 도메인 DTO에 중첩 record 패턴 도입
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/domain/Contest.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestMedalSummaryDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestMedalSummaryResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordCreateCommand.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordCreateDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordCreateRequestDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordCreateResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDeleteCommand.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDeleteDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDeleteResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDetailDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDetailResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordSimpleDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordSimpleResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordUpdateDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordUpdateRequestDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordUpdateResponseDTO.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java
Labels: 🌟 REFACT

#87 [feat/#86] 대표 주소 변경API 구현
  src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
Labels: 🛠️ FEAT

#97 [feat/#94] 회원 주소 삭제 API 구현
  src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
  src/main/java/umc/cockple/demo/domain/member/domain/Member.java
  src/main/java/umc/cockple/demo/domain/member/exception/MemberErrorCode.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
Labels: 🛠️ FEAT

#99 [refactor/#98] 주소 추가 로직 수정
  src/main/java/umc/cockple/demo/domain/member/dto/CreateMemberAddrDTO.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
Labels: 🌟 REFACT

#91 [refactor/#89] 모임 생성 API 이미지 업로드 방식 변경
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateCommand.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateRequestDTO.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🌟 REFACT

#93 [refactor/#92] 모임 도메인 DTO에 중첩 record 패턴 도입
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyAddrCreateCommand.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateCommand.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateRequestDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateResponseDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinActionDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinActionRequestDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinCreateDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinCreateResponseDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinResponseDTO.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
Labels: 🌟 REFACT

#108 [fix/#107] 병합 오류 해결
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinActionDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinCreateDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinDTO.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
Labels: 🕷️ BUG

#105 [refactor#102] MemberExercise와 Guest에서 participantNum 필드 제거
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/domain/Exercise.java
  src/main/java/umc/cockple/demo/domain/exercise/domain/Guest.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseCancelDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseGuestInviteDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseJoinDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
  src/main/java/umc/cockple/demo/domain/member/domain/MemberExercise.java
Labels: 🌟 REFACT

#106 [feat/#103] 운동 신청 API에서 검증 로직 추가
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/exception/ExerciseErrorCode.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
  src/main/java/umc/cockple/demo/domain/member/domain/Member.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
Labels: 🛠️ FEAT

#118 [feat/#95] 프로필 조회 관련 API 구현
  src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
  src/main/java/umc/cockple/demo/domain/member/converter/MemberConverter.java
  src/main/java/umc/cockple/demo/domain/member/dto/GetMyProfileResponseDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/GetProfileResponseDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/request/UpdateProfileRequestDTO.java
  src/main/java/umc/cockple/demo/domain/member/exception/MemberErrorCode.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberQueryService.java
Labels: 🛠️ FEAT

#117 [feat/#110] 모임 신청 API 검증 로직 추가 구현
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
  src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🛠️ FEAT

#119 [Feat/#96] 회원 주소 조회 관련 API 구현
  src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
  src/main/java/umc/cockple/demo/domain/member/converter/MemberConverter.java
  src/main/java/umc/cockple/demo/domain/member/domain/MemberAddr.java
  src/main/java/umc/cockple/demo/domain/member/dto/CreateMemberAddrDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/GetAllAddressResponseDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/GetMyProfileResponseDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/GetNowAddressResponseDTO.java
  src/main/java/umc/cockple/demo/domain/member/dto/GetProfileResponseDTO.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberQueryService.java
Labels: 🛠️ FEAT

#127 [feat/#124] 모임 가입 승인 멤버 조회 API 구현
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinActionDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinDTO.java
  src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
Labels: 🛠️ FEAT

#128 [feat/#78] 운동 상세 조회 API 구현
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseDetailDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/GuestRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
  src/main/java/umc/cockple/demo/domain/member/domain/MemberExercise.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberPartyRepository.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberRepository.java
  src/main/java/umc/cockple/demo/global/enums/ExerciseMemberShipStatus.java
Labels: 🛠️ FEAT

#129 [feat/#122] 모임 상세 조회 API 구현
  src/main/java/umc/cockple/demo/domain/member/repository/MemberPartyRepository.java
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyDetailDTO.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
  src/main/java/umc/cockple/demo/global/enums/ActiveDay.java
  src/main/java/umc/cockple/demo/global/enums/ActivityTime.java
  src/main/java/umc/cockple/demo/global/enums/Keyword.java
  src/main/java/umc/cockple/demo/global/enums/Level.java
Labels: 🛠️ FEAT

#134 [feat/#131] 내 모임 조회 (간략화) API 구현
  src/main/java/umc/cockple/demo/domain/member/repository/MemberPartyRepository.java
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartySimpleDTO.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
Labels: 🛠️ FEAT

#133 [feat/#132] 내가 초대한 운동 게스트 조회 API 구현
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseMyGuestListDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/GuestRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
Labels: 🛠️ FEAT

#139 [refactor/#138] orphanRemoval 제거
  src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
  src/main/java/umc/cockple/demo/domain/member/domain/Member.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberPartyRepository.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
Labels: 🌟 REFACT

#156 [feat/#153] 내 운동 캘린더 조회 API 구현
  .gitignore
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/MyExerciseCalendarDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
Labels: 🛠️ FEAT

#167 [feat/#166] 모임 운동 캘린더 조회 API에 찜 여부 추가
  src/main/java/umc/cockple/demo/domain/bookmark/repository/ExerciseBookmarkRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/PartyExerciseCalendarDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
Labels: 🛠️ FEAT

#170 [feat/#149] 운동 도메인에 빈 응답 조기 반환(Early Return) 패턴 도입
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
Labels: 🛠️ FEAT

#176 [refactor/#175] 모임 활동상태 검증 메서드 추가
  src/main/java/umc/cockple/demo/domain/bookmark/service/BookmarkCommandService.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
  src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
Labels: 🌟 REFACT

#179 [feat/#165] 내 모임 운동 캘린더 조회 API 구현
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/MyPartyExerciseCalendarDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
  src/main/java/umc/cockple/demo/global/enums/MyPartyExerciseOrderType.java
Labels: 🛠️ FEAT

#180 [feat/#178] 모임 멤버 조회 API 구현
  src/main/java/umc/cockple/demo/domain/member/repository/MemberPartyRepository.java
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyMemberDTO.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
  src/main/java/umc/cockple/demo/global/enums/Role.java
Labels: 🛠️ FEAT

#181 [feat/#177] 캘린더 조회 API에서 날짜별로 아이템 묶기
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/MyExerciseCalendarDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/PartyExerciseCalendarDTO.java
Labels: 🛠️ FEAT

#173 [feat/#172] 대회 이미지 업로드 API 구현
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/image/controller/ImgController.java
  src/main/java/umc/cockple/demo/domain/image/dto/ImageUploadResponseDTO.java
  src/main/java/umc/cockple/demo/domain/image/dto/PresignedUrlResponseDTO.java
  src/main/java/umc/cockple/demo/domain/image/service/ImageService.java
  src/main/java/umc/cockple/demo/global/enums/ImgType.java
Labels: 🛠️ FEAT

#187 [feat/#137] 모임 멤버 삭제 API 구현
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🛠️ FEAT

#184 [feat/#161] 읽지 않은 알림 여부 조회
  src/main/java/umc/cockple/demo/domain/notification/controller/NotificationController.java
  src/main/java/umc/cockple/demo/domain/notification/dto/ExistNewNotificationResponseDTO.java
  src/main/java/umc/cockple/demo/domain/notification/service/NotificationQueryService.java
Labels: 🛠️ FEAT

#190 [feat/#188] 모임 추천 조회 API 구현
  src/main/java/umc/cockple/demo/domain/member/repository/MemberAddrRepository.java
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/repository/PartyRepository.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
Labels: 🛠️ FEAT

#191 [feat/#164] 추천 운동 조회 API 구현
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseRecommendationDTO.java
  src/main/java/umc/cockple/demo/domain/exercise/exception/ExerciseErrorCode.java
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberRepository.java
Labels: 🛠️ FEAT

#196 [refactor/#194] 도메인별 ENUM 패키지 구조 개선
  src/main/java/umc/cockple/demo/domain/bookmark/controller/BookmarkController.java
  src/main/java/umc/cockple/demo/domain/bookmark/converter/BookmarkConverter.java
  src/main/java/umc/cockple/demo/domain/bookmark/domain/PartyBookmark.java
  src/main/java/umc/cockple/demo/domain/bookmark/dto/GetAllPartyBookmarkResponseDTO.java
  src/main/java/umc/cockple/demo/domain/bookmark/enums/BookmarkedExerciseOrderType.java
  src/main/java/umc/cockple/demo/domain/bookmark/service/BookmarkCommandService.java
  src/main/java/umc/cockple/demo/domain/bookmark/service/BookmarkQueryService.java
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/domain/Contest.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordCreateDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDetailDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordSimpleDTO.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordUpdateDTO.java
  src/main/java/umc/cockple/demo/domain/contest/enums/MedalType.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java
  src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
  src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
  src/main/java/umc/cockple/demo/domain/exercise/domain/Guest.java
  src/main/java/umc/cockple/demo/domain/exercise/enums/ExerciseMemberShipStatus.java
  src/main/java/umc/cockple/demo/domain/exercise/enums/MyPartyExerciseOrderType.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
  src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
  src/main/java/umc/cockple/demo/domain/member/domain/Member.java
  src/main/java/umc/cockple/demo/domain/member/domain/MemberExercise.java
  src/main/java/umc/cockple/demo/domain/member/domain/MemberParty.java
  src/main/java/umc/cockple/demo/domain/member/enums/MemberPartyStatus.java
  src/main/java/umc/cockple/demo/domain/member/enums/MemberStatus.java
  src/main/java/umc/cockple/demo/domain/member/repository/MemberExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
  src/main/java/umc/cockple/demo/domain/member/service/MemberQueryService.java
  src/main/java/umc/cockple/demo/domain/notification/controller/NotificationController.java
  src/main/java/umc/cockple/demo/domain/notification/domain/Notification.java
  src/main/java/umc/cockple/demo/domain/notification/dto/AllNotificationsResponseDTO.java
  src/main/java/umc/cockple/demo/domain/notification/dto/MarkAsReadDTO.java
  src/main/java/umc/cockple/demo/domain/notification/enums/NotificationType.java
  src/main/java/umc/cockple/demo/domain/notification/service/NotificationCommandService.java
  src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
  src/main/java/umc/cockple/demo/domain/party/domain/PartyActiveDay.java
  src/main/java/umc/cockple/demo/domain/party/domain/PartyJoinRequest.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinActionDTO.java
  src/main/java/umc/cockple/demo/domain/party/enums/ActiveDay.java
  src/main/java/umc/cockple/demo/domain/party/enums/ActivityTime.java
  src/main/java/umc/cockple/demo/domain/party/enums/ParticipationType.java
  src/main/java/umc/cockple/demo/domain/party/enums/PartyOrderType.java
  src/main/java/umc/cockple/demo/domain/party/enums/PartyStatus.java
  src/main/java/umc/cockple/demo/domain/party/enums/RequestAction.java
  src/main/java/umc/cockple/demo/domain/party/enums/RequestStatus.java
  src/main/java/umc/cockple/demo/domain/party/repository/PartyJoinRequestRepository.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
  src/main/java/umc/cockple/demo/global/enums/ExerciseOrderType.java
  src/main/java/umc/cockple/demo/global/enums/MemberStatus.java
Labels: 🌟 REFACT

#197 [refactor/#189] 대회 등록 API에서 이미지 업로드 분리
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordCreateDTO.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
Labels: 🌟 REFACT

#200 [refactor/#199] 대회 기록 수정 API에서 이미지 업로드 분리
  src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
  src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordUpdateDTO.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
  src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
Labels: 🌟 REFACT

#219 [refact/#214] 나이대 변수명 변경
  src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
  src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateDTO.java
  src/main/java/umc/cockple/demo/domain/party/dto/PartyDetailDTO.java
  src/main/java/umc/cockple/demo/domain/party/repository/PartyRepository.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🌟 REFACT

#218 [feat/#217] 모임 생성 시 자동으로 모임 채팅방 생성 로직 구현
  src/main/java/umc/cockple/demo/domain/chat/domain/ChatRoom.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
  src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomRepository.java
  src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
  src/main/java/umc/cockple/demo/domain/party/domain/Party.java
  src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
Labels: 🛠️ FEAT
